;NAME- ARPAN SAHU
;REGD. NO.-2341019235

MOV AX,5544H   ; STORES DATA 1234H IN AX
MOV BX,2345H   ; STORES DATA 2345H IN BX
MOV CX,AX      ; MOVES DATA OF AX TO CX
ADD AX,BX      ; ADDS VALUE STORED IN AX WITH VALUE STORED IN BX
MOV [4500H],AX ; MOVES RESULT OF ADDITION STORED IN AX TO THE LOCATION 4500H   
MOV AX,CX      ; COPIES DATA OF CX TO AX 
SUB AX,BX      ; SUBTRACTS DATA OF BX FROM AX AND STORES RESULT IN AX
MOV [4502H],AX ; COPIES DATA OF AX TO 4502H LOCATION
MOV AX,CX      ; AX TAKES DATA STORED IN CX
MUL BX         ; AX MULTIPLIED WITH BX
MOV [4504H],AX ; COPIES DATA TO LOCATION 4504H
MOV [4506H],DX
MOV DX,0000H   ; ASSIGNING VALUE 0000 TO DX
MOV AX,CX
DIV BX         ; DIVISION OF AX BY BX
MOV [4508H],AX 
MOV [450AH],DX
HLT            ; TO STOP THE PROGRAM